backend:
  name: git-gateway
  branch: master

local_backend: false

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads

collections:
  - name: "result" # Used in routes, e.g., /admin/collections/blog
    format: json
    label: "Resultaat" # Used in the UI
    folder: "_data/clubrecords" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{datum}}-{{geslacht}}-{{locatie}}-{{categorie}}-{{onderdeel}}" # Filename template, e.g., YYYY-MM-DD-title.md
    summary: "{{onderdeel}} - {{naam}} ({{datum}})"
    sortableFields: ['datum']
    fields: # The fields for each document, usually in front matter
      - {label: "Atleet", name: "naam", widget: "string"}
      - label: "Categorie"
        default: "Senioren"
        name: "categorie"
        widget: "select"
        options:
          - "Senioren"
          - "Junioren A"
          - "Junioren B"
          - "Junioren C"
          - "Junioren D"
          - "Wegatletiek"
      - label: "Geslacht"
        name: "geslacht"
        widget: "select"
        default: "Vrouwen"
        options:
          - { label: "Vrouw", value: "Vrouwen" }
          - { label: "Man", value: "Mannen" }
      - label: "Indoor/outdoor"
        name: "locatie"
        default: "outdoor"
        widget: "select"
        options:
          - { label: "Indoor", value: "indoor" }
          - { label: "Outdoor", value: "outdoor" }
      - label: "Onderdeel"
        name: "onderdeel"
        widget: "select"
        options:
          - "30 m"
          - "35 m"
          - "40 m"
          - "50 m"
          - "60 m"
          - "80 m"
          - "100 m"
          - "150 m"
          - "200 m"
          - "300 m"
          - "400 m"
          - "600 m"
          - "800 m"
          - "1 000 m"
          - "1 500 m"
          - "1 Engelse mijl"
          - "10 Engelse mijl"
          - "2 000 m"
          - "3 000 m"
          - "5 000 m"
          - "10 km"
          - "15 km"
          - "20 km"
          - "Halve marathon"
          - "25 km"
          - "30 km"
          - "35 km"
          - "Marathon"
          - "100 km"
          - "40 m horden"
          - "60 m horden"
          - "60 m horden"
          - "80 m horden"
          - "100 m horden"
          - "110 m horden"
          - "300 m horden"
          - "400 m horden"
          - "4 x 60 m"
          - "4 x 80 m"
          - "4 x 100 m"
          - "4 x 200 m"
          - "4 x 400 m"
          - "4 x 800 m"
          - "4 x 1500 m"
          - "Zweedse estafette"
          - "3 km snelwandelen"
          - "5 km snelwandelen"
          - "10 km snelwandelen"
          - "1 500 m steeplechase"
          - "2 000 m steeplechase"
          - "3 000 m steeplechase"
          - "1 uur"
          - "Balwerpen"
          - "Hoogspringen"
          - "Verspringen"
          - "Gewichtwerpen"
          - "Kogelstoten"
          - "Kogelslingeren"
          - "Polsstokhoogspringen"
          - "Hinkstapspringen"
          - "Discuswerpen"
          - "Speerwerpen"
          - "Vijfkamp"
          - "Zeskamp"
          - "Zevenkamp"
          - "Achtkamp"
          - "Tienkamp"
      - {label: "Prestatie", name: "prestatie", widget: "code"}
      - {label: "Handtijd", name: "handtijd", widget: "string", hint: "Indien deze tijd ook met de hand is geklokt kan dit hier worden ingevuld.", required: false }
      - {label: "Plaats", name: "plaats", widget: "string"}
      - {label: "Datum", hint: "Indien het om een meerkamp gaat mag je dit veld gebruiken als startdatum van de wedstrijd", name: "datum", widget: "datetime", format: 'DD-MM-YYYY', dateFormat: 'DD-MM-YYYY', timeFormat: ''}
      - {label: "(eind)datum", hint: "Einddatum van de wedstrijd indien het om een meerkamp gaat", name: "einddatum", default: "", widget: "datetime", format: 'DD-MM-YYYY', dateFormat: 'DD-MM-YYYY', timeFormat: '', required: false }
      - {label: "Link", name: "link", widget: "string", required: false}
